name: Java CI
on: [push, pull_request]

jobs:
  team-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install PyGithub

      - name: Run team info script
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_ACCESS_TOKEN }}
        run: python .github/scripts/team_info.py

  checkstyle:
    runs-on: ubuntu-latest
    needs: team-info  # Зависит от новой стадии
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain

  # Stage 2 - Билд проекта
  build:
    runs-on: ubuntu-latest
    needs: checkstyle
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Build project
        run: ./gradlew build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build/libs/
          retention-days: 1

  # Stage 3 - Прогон тестов
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run tests
        run: echo "Выполняется прогон тестов проекта..."

  # Stage 4 - Публикация сборки
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - name: Publish build
        run: echo "Публикация сборки проекта..."