name: Java CI
on: 
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  team-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install PyGithub

      - name: Run team info script
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_ACCESS_TOKEN }}
        run: python .github/scripts/team_info.py

  check-mr-size:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install PyGithub

      - name: Check MR size
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_ACCESS_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: python .github/scripts/team_info.py check-mr

  checkstyle:
    runs-on: ubuntu-latest
    needs: [team-info, check-mr-size]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain

  build:
    runs-on: ubuntu-latest
    needs: checkstyle
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Build project
        run: ./gradlew build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build/libs/
          retention-days: 1

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run tests
        run: echo "Выполняется прогон тестов проекта..."

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - name: Publish build
        run: echo "Публикация сборки проекта..."