name: Java CI
on: [push, pull_request]

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain

  build:
    runs-on: ubuntu-latest
    needs: checkstyle 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Build project
        run: ./gradlew build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build/libs/
          retention-days: 1

  test:
    runs-on: ubuntu-latest
    needs: build 
    steps:
      - name: Run tests
        run: echo "Выполняется прогон тестов проекта..."


  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - name: Publish build
        run: echo "Публикация сборки проекта..."